name: scale production

on:
  workflow_dispatch:
    inputs:
      scale:
        description: 'Scale type (idle or event)'
        required: true
        default: 'idle'
        type: choice
        options:
          - idle
          - event

  # Run on Monday at midnight to scale back to idle
  schedule:
    - cron: '0 0 * * 1'

permissions:
  id-token: write

jobs:
  scale:
    runs-on: ubuntu-latest
    environment: prod
    env:
      DB_CAPACITY_IDLE: 10
      DB_CAPACITY_EVENT: 50
      APP_SVC_PLAN_SKU_IDLE: B1
      APP_SVC_PLAN_SKU_EVENT: P1v3
    steps:
      - name: azure login
        uses: Azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: set values (idle)
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.scale == 'idle' ) || github.event_name == 'schedule'
        run: |
          echo "APP_SVC_PLAN_SKU=${{ env.APP_SVC_PLAN_SKU_IDLE }}" >> $GITHUB_ENV
          echo "DB_CAPACITY=${{ env.DB_CAPACITY_IDLE }}" >> $GITHUB_ENV

      - name: set values (event)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.scale == 'event'
        run: |
          echo "APP_SVC_PLAN_SKU=${{ env.APP_SVC_PLAN_SKU_EVENT }}" >> $GITHUB_ENV
          echo "DB_CAPACITY=${{ env.DB_CAPACITY_EVENT }}" >> $GITHUB_ENV

      - name: scale
        uses: azure/cli@089eac9d8cc39f5d003e94f8b65efc51076c9cbd # v2.1.0
        if: env.APP_SVC_PLAN_SKU && env.DB_CAPACITY
        with:
          azcliversion: latest
          inlineScript: |
            # Set app service plan SKU
            az appservice plan update \
              --name ${{ secrets.APP_SERVICE_PLAN_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
              --sku ${{ env.APP_SVC_PLAN_SKU }}

            # Set SQL Database SKU
            az sql db update \
              --name ${{ secrets.SQL_DATABASE_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
              --server ${{ secrets.SQL_SERVER_NAME }} \
              --capacity ${{ env.DB_CAPACITY }}
